"""drop base64 image columns

Revision ID: 06dc7b04d95b
Revises: 45b19db879f2
Create Date: 2026-07-29 19:33:30.599774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dc7b04d95b'
down_revision: Union[str, Sequence[str], None] = '45b19db879f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_requests', 'document_image_data')
    op.drop_column('verification_requests', 'secondary_document_image_data')
    op.drop_column('verification_requests', 'selfie_image_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_requests', sa.Column('selfie_image_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verification_requests', sa.Column('secondary_document_image_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verification_requests', sa.Column('document_image_data', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
