"""add new profile fields

Revision ID: 09b4cdf0f6d9
Revises: c976e11f95b3
Create Date: 2026-07-24 17:35:07.576544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09b4cdf0f6d9'
down_revision: Union[str, Sequence[str], None] = 'c976e11f95b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_messages_sender_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_user_id'), table_name='support_messages')
    op.drop_table('support_messages')
    # NOTE: keep verification_requests and users.verification_status introduced by other migration
    # The following drop was removed during merge resolution to preserve the verification system:
    # op.drop_index(op.f('ix_verification_requests_user_id'), table_name='verification_requests')
    # op.drop_table('verification_requests')
    op.add_column('guest_profiles', sa.Column('unit_description', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('giving_to_host', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('guest_profiles', sa.Column('food_allergies', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('food_preferences', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('religious_level', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('kosher_food', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('guest_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('guest_address', sa.String(), nullable=True))
    op.drop_column('guest_profiles', 'food_preferences_allergies')
    op.drop_column('guest_profiles', 'is_soldier_or_national_service')
    op.drop_column('guest_profiles', 'origin_city')
    op.drop_column('guest_profiles', 'skills_give_take')
    op.drop_column('guest_profiles', 'unit_name')
    op.add_column('host_profiles', sa.Column('residential_address', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('neighborhood_type', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('num_beds', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('host_profiles', sa.Column('pets_description', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('housing_type', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('accessibility_level', sa.String(), nullable=True))
    op.alter_column('host_profiles', 'num_bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_host_profiles_city'), table_name='host_profiles')
    op.drop_column('host_profiles', 'has_pets')
    op.drop_column('host_profiles', 'neighborhood')
    op.drop_column('host_profiles', 'religious_orientation')
    op.drop_column('host_profiles', 'free_text_notes')
    op.drop_column('host_profiles', 'accessibility')
    op.drop_column('host_profiles', 'city')
    op.drop_column('host_profiles', 'full_address')
    # Keep users.verification_status (added in a different migration) to match current models
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_status', sa.VARCHAR(length=32), server_default=sa.text("'pending_submission'::character varying"), autoincrement=False, nullable=False))
    op.add_column('host_profiles', sa.Column('full_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('host_profiles', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('host_profiles', sa.Column('accessibility', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('host_profiles', sa.Column('free_text_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('host_profiles', sa.Column('religious_orientation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('host_profiles', sa.Column('neighborhood', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('host_profiles', sa.Column('has_pets', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_host_profiles_city'), 'host_profiles', ['city'], unique=False)
    op.alter_column('host_profiles', 'num_bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('host_profiles', 'accessibility_level')
    op.drop_column('host_profiles', 'housing_type')
    op.drop_column('host_profiles', 'pets_description')
    op.drop_column('host_profiles', 'num_beds')
    op.drop_column('host_profiles', 'neighborhood_type')
    op.drop_column('host_profiles', 'residential_address')
    op.add_column('guest_profiles', sa.Column('unit_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guest_profiles', sa.Column('skills_give_take', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('guest_profiles', sa.Column('origin_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guest_profiles', sa.Column('is_soldier_or_national_service', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('guest_profiles', sa.Column('food_preferences_allergies', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('guest_profiles', 'guest_address')
    op.drop_column('guest_profiles', 'gender')
    op.drop_column('guest_profiles', 'kosher_food')
    op.drop_column('guest_profiles', 'religious_level')
    op.drop_column('guest_profiles', 'food_preferences')
    op.drop_column('guest_profiles', 'food_allergies')
    op.drop_column('guest_profiles', 'giving_to_host')
    op.drop_column('guest_profiles', 'unit_description')
    op.create_table('verification_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selfie_image_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('document_image_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('verification_type', sa.VARCHAR(length=32), server_default=sa.text("'civilian'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending_ai'::character varying"), autoincrement=False, nullable=False),
    sa.Column('ai_confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('selfie_image_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_image_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secondary_document_image_path', sa.VARCHAR(length=512), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('secondary_document_image_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('verification_requests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_requests_pkey'))
    )
    op.create_index(op.f('ix_verification_requests_user_id'), 'verification_requests', ['user_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('support_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('support_messages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('support_messages_pkey'))
    )
    op.create_index(op.f('ix_support_messages_user_id'), 'support_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_support_messages_sender_id'), 'support_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###
