"""add is_soldier_or_national_service to guest_profiles

Revision ID: 0f56c2c647f9
Revises: 02c161ae53d4
Create Date: 2026-07-24 18:39:04.027349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f56c2c647f9'
down_revision: Union[str, Sequence[str], None] = '02c161ae53d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_profiles', sa.Column('is_soldier_or_national_service', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'verification_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('pending_submission', 'pending_ai', 'pending_admin', 'approved', 'rejected', 'suspended', name='userverificationstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_submission'::character varying"))
    op.alter_column('verification_requests', 'verification_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('lone_soldier', 'civilian', 'new_immigrant', name='verificationtype', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'civilian'::character varying"))
    op.alter_column('verification_requests', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('pending_ai', 'pending_admin', 'approved', 'rejected', name='verificationstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_ai'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_requests', 'status',
               existing_type=sa.Enum('pending_ai', 'pending_admin', 'approved', 'rejected', name='verificationstatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_ai'::character varying"))
    op.alter_column('verification_requests', 'verification_type',
               existing_type=sa.Enum('lone_soldier', 'civilian', 'new_immigrant', name='verificationtype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'civilian'::character varying"))
    op.alter_column('users', 'verification_status',
               existing_type=sa.Enum('pending_submission', 'pending_ai', 'pending_admin', 'approved', 'rejected', 'suspended', name='userverificationstatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_submission'::character varying"))
    op.drop_column('guest_profiles', 'is_soldier_or_national_service')
    # ### end Alembic commands ###
