import uuid
from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, Text, Boolean, JSON, text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func
from app.database.base import Base

class AdminAlert(Base):
    """Urgent alerts generated by the system for admin review."""
    __tablename__ = "admin_alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )
    alert_type: Mapped[str] = mapped_column(default="severe_review")
    # If the alert is about a specific review/user, we can store IDs or JSON
    reference_id: Mapped[uuid.UUID] = mapped_column(nullable=True) 
    payload: Mapped[dict] = mapped_column(JSON) # Store Guest, Host, Review details
    is_resolved: Mapped[bool] = mapped_column(Boolean, default=False, server_default=text("false"))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        server_default=func.now(),
    )
